name: lausanne-heat-islands
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - -e .
    - flake8-isort==2.7.0
    - urban-footprinter==0.0.1
  - setuptools
  - wheel
  - click
  - sphinx
  - coverage
  - flake8
  - awscli  
  - python-dotenv>=0.5.1
  - python=3.7
  - ipykernel
  - boto3
  - tqdm
  - numpy<=1.16
  - laspy
  - geopandas
  - rasterio
  - opencv
